name: CI hello-world action

on:
  push:
    paths:
      - '.github/workflows/ci.yml'
      - 'actions/hello-world/*'

jobs:
  build:
    name: Build hello-world action
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install NodeJS
        uses: actions/setup-node@8f152de45cc393bb48ce5d89d36b731f54556e65 # v4
        with:
          node-version: 16.x

      - name: Build latest version for testing
        run: |
          npm install
          npm run build
        working-directory: actions/hello-world

      - name: hello-world with "important" as false
        uses: ./actions/hello-world
        with:
          important: false

      - name: hello-world with "important" as true
        uses: ./actions/hello-world
        with:
          important: true

      - name: hello-world without "important"
        uses: ./actions/hello-world
