name: Foo & Bar

on:
  push:
    paths:
      - actions/foo
      - actions/bar

jobs:
  main:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Say hello from foo
        uses: mongrelion/github-actions-lab/actions/foo@main

      - name: Say hello from bar
        uses: mongrelion/github-actions-lab/actions/bar@main
